[versions]
moddev-gradle = "2.0.134"
fabric-loom = "1.14.10"
mod-publish-plugin = "1.1.0"

[libraries]
moddev-gradle = {group = "net.neoforged", name = "moddev-gradle",  version.ref = "moddev-gradle"}
fabric-loom = {group = "net.fabricmc", name = "fabric-loom", version.ref = "fabric-loom"}
mod-publish-plugin = {group = "me.modmuss50", name = "mod-publish-plugin", version.ref = "mod-publish-plugin"}
